package it.polimi.ingsw.client.ClientModel.enumerations;

public enum LorenzoCardType {
 DISCARD2GREENDVCARDS,
 DISCARD2YELLOWDVCARDS,
 DISCARD2BLUEDVCARDS,
 DISCARD2VIOLETDVCARDS,
 TWOFAITHPOINTSCARD,
 FAITHANDSHUFFLECARD
};

