package it.polimi.ingsw.model.enumerations;

public enum LorenzoCardsType {
 DISCARD2GREENDVCARDS, DISCARD2YELLOWDVCARDS, DISCARD2BLUEDVCARDS, DISCARD2VIOLETDVCARDS, TWOFAITHPOINTSCARD, FAITHANDSHUFFLECARD

}
