package it.polimi.ingsw.model.enumerations;

public enum LorenzoCardsTypes {
 DISCARD2GREENDVCARDS,
 DISCARD2YELLOWDVCARDS,
 DISCARD2BLUEDVCARDS,
 DISCARD2VIOLETDVCARDS,
 TWOFAITHPOINTSCARD,
 FAITHANDSHUFFLECARD
};

